### PR TITLE
Typo in exports?

### PR DESCRIPTION
**Pull request by LnL7**
Should export to `window.drykup`

### CODE REVIEW

**Comment by mark-hahn** [comment]
Thanks.  I obviously had not tested usage in the browser in that version.  Now that I look at it there is another bug in the same line.  `module.export` should be `module?.export`

I have used drykup a lot but I haven't kept this repo up-to-date.  There didn't appear to be any interest.  When I get a chance I will update it.  Meanwhile if anyone wants a copy of the version I'm using in production let me know.

**Comment by LnL7** [comment]
I thought about `module?.exports` but was not entirely sure.

I'd love to take a look at your latest version,
and tips/examples about using it with express would be nice.

Your idea about direct dom manipulation sounds very interesting.

**Comment by mark-hahn** [comment]
Here is the file.  I should warn you that I may have put in kludges
specific to my app in moments of laziness.

I have also added more shortcuts to my expand feature, but there may not be
many (or any) others who would use such shorthand.  I myself could not live
without it.

If you have any changes in my file that you think should be in the master
repo, please issue pull requests.  I should do it but I am on deadline and
don't have time.

I am sorry but I don't use express.  I have never found a need for it.

Let me know what you think of it if you start using it.  I have used it for
almost a year.

P.S.  I have a new design in my head that I want to implement between
projects.  It will have an option to generate DOM elements directly instead
of just producing html.  I also would like to add some features to improve
it's usage with backbonejs.

**Comment by mark-hahn** [comment]
Oops, the file didn't go through from email. Here it is in a gist ...  https://gist.github.com/2984179

**Pull request merged**
